// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var CheckBox$ReactTemplate = require("./utilComponents/CheckBox.bs.js");
var HorizontalSpacer$ReactTemplate = require("./utilComponents/HorizontalSpacer.bs.js");

var component = ReasonReact.reducerComponent("todoItem");

function str(prim) {
  return prim;
}

function make(description, showCompleted, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              var send = param[/* send */3];
              var state = param[/* state */1];
              var match = !showCompleted && state[/* completed */1];
              if (match) {
                return "";
              } else {
                return React.createElement("div", {
                            className: "contentRow",
                            onClick: (function (param) {
                                return Curry._1(send, /* Click */0);
                              })
                          }, ReasonReact.element(undefined, undefined, CheckBox$ReactTemplate.make("black", state[/* completed */1], /* array */[])), ReasonReact.element(undefined, undefined, HorizontalSpacer$ReactTemplate.make("50", /* array */[])), React.createElement("div", {
                                className: "todoItem"
                              }, state[/* description */0]));
              }
            }),
          /* initialState */(function (param) {
              return /* record */[
                      /* description */description,
                      /* completed */false
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              return /* Update */Block.__(0, [/* record */[
                          /* description */state[/* description */0],
                          /* completed */!state[/* completed */1]
                        ]]);
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.str = str;
exports.make = make;
/* component Not a pure module */
