// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var CheckBox$ReactTemplate = require("./utilComponents/CheckBox.bs.js");
var HorizontalSpacer$ReactTemplate = require("./utilComponents/HorizontalSpacer.bs.js");

var component = ReasonReact.statelessComponent("todoItem");

function str(prim) {
  return prim;
}

function make(description, showCompleted, completed, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              var match = !showCompleted && completed;
              if (match) {
                return "";
              } else {
                return React.createElement("div", {
                            className: "contentRow"
                          }, ReasonReact.element(undefined, undefined, CheckBox$ReactTemplate.make("black", completed, /* array */[])), ReasonReact.element(undefined, undefined, HorizontalSpacer$ReactTemplate.make("50", /* array */[])), React.createElement("div", {
                                className: "todoItem"
                              }, description));
              }
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.str = str;
exports.make = make;
/* component Not a pure module */
