// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';


var initialState = /* record */[
  /* count */0,
  /* showCompleted */true,
  /* todos : [] */0,
  /* todoText */""
];

exports.initialState = initialState;
/* No side effect */
